// Generated by CoffeeScript 1.6.2
(function() {
  var Qchan;

  Qchan = {};

  Qchan.URIFragmentParser = (function() {
    URIFragmentParser.parse = function(fragment) {
      return new this(fragment).parse();
    };

    function URIFragmentParser(fragment) {
      this.fragment = fragment;
    }

    URIFragmentParser.prototype.parse = function() {
      var key, segment, table, value, _i, _len, _ref, _ref1;

      table = {};
      _ref = this.segments();
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        segment = _ref[_i];
        _ref1 = segment.split('=', 2), key = _ref1[0], value = _ref1[1];
        if (value) {
          table[key] = window.decodeURIComponent(value);
        }
      }
      return table;
    };

    URIFragmentParser.prototype.segments = function() {
      return this.fragment.substr(1).split('&');
    };

    return URIFragmentParser;

  })();

  console.log(Qchan.URIFragmentParser.parse(window.location.hash));

}).call(this);
